DIN-207 [DPS] Set up your wallet
SayNode/dinasona-flutter pull request #109
Opened 2024-11-27 16:27 UTC by MoizesFSantos

2024-11-27 17:15 UTC, curtis2101 requested changes

2024-11-27 17:15 UTC, curtis2101 commented on lib/pages/create_new_need/wallet_instructions.dart
> +                  ? 'To donate and support people, you first need to set up a wallet.'
add tr here

2024-11-27 17:33 UTC, MoizesFSantos commented on lib/pages/create_new_need/wallet_instructions.dart
> +                  ? 'To donate and support people, you first need to set up a wallet.'
sorry I forgot

2024-11-28 09:09 UTC, curtis2101 approved these changes

2024-11-28 09:41 UTC, merged